feature: navigation tabBar button
openworld-community/ows-events-mobile pull request #167
Opened 2023-08-18 19:05 UTC by GhostJavaWriter

2023-08-18 20:37 UTC, leksidev commented
Привет. А почему ты решил поменять виджет? Я посмотрела, но не поняла, чем не подошел существующий?

2023-08-18 21:01 UTC, GhostJavaWriter commented
У старого виджета не нашел propertie selected label и он не красил лейбу

2023-08-19 09:26 UTC, leksidev requested changes
Нужно добавить проверку платформы и выводить для устройств Эппл навигационную панель купертино, а не материал, а для Андроид оставить материал. Ссылку скинула в Телегу.

2023-08-20 10:53 UTC, closed without merging

2023-08-20 10:53 UTC, MariannaKhanina commented
Решено оставить подгонку внешнего вида на конец, когда будем понятна разница в дизайнах между платформами