Added created_event_menu.dart and rounded_text_field.dart
openworld-community/ows-events-mobile pull request #19
Opened 2023-06-14 15:54 UTC by ArkadiiIL

Добавил created_event_menu которое является алерт диалогом, пока открывается при нажати на эвенты, пока не добавлял выбор времени и даты, там нужно какую-нибудь библиотку прикрутить, если вообще нужно. Сделал кастомный textfield с обводкой и очисткой текста по значку. Ширину тоже не устанавливал. 
Выглядит прмерно так 
![image](https://github.com/openworld-community/ows-events-mobile/assets/47066674/6f78bf5a-b580-4be7-a512-1dc30f902434)

2023-06-16 19:29 UTC, MariannaKhanina requested changes

2023-06-16 19:29 UTC, MariannaKhanina commented on lib/main.dart
>  import 'package:dio/dio.dart';
Меня видно?

2023-06-16 20:57 UTC, ArkadiiIL commented on lib/resources/text_styles.dart
> -  static const TextStyle mainTextStyle = TextStyle(
Так в отдельной таске делать? Не тут же?

2023-06-16 21:00 UTC, ArkadiiIL commented on lib/widgets/create_event_menu.dart
> +    return AlertDialog(
Может вытащить начиная с SingleChildScrollView в отдельный виджет и сам экран уже отдельным фаилом

2023-06-18 19:10 UTC, MariannaKhanina approved these changes

2023-06-18 19:10 UTC, merged