Нарисовать MVP ячейки списка событий #201
openworld-community/ows-events-mobile pull request #3
Opened 2023-05-31 03:46 UTC by ArkadiiIL

https://github.com/openworld-community/ows-events/issues/201
Написал виджет, не уверен, что там делать с шириной.
Добавил папку ресурсов с цветами и стилями текста.
Еще добавил папку ассетов и там картинка для теста в игнор ее не добавлял.

2023-05-31 16:16 UTC, IlyaGulya requested changes

2023-05-31 16:16 UTC, IlyaGulya commented on lib/widgets/EventListItem.dart
> +  });
Хорошо бы добавить сразу на элемент поддержку клика + Ripple эффект (ну или какой там у флаттера дефолтный вариант реакции на нажатие)

2023-05-31 16:16 UTC, IlyaGulya commented on lib/widgets/EventListItem.dart
> +        Container(
Линтер ругается, говорит что где это возможно лучше юзать SizedBox:
https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html

<img width="530" alt="image" src="https://github.com/openworld-community/ows-events-mobile/assets/668727/85ad77e4-468b-40f1-b610-a07d8f9f26e8">

2023-05-31 20:14 UTC, ArkadiiIL commented on lib/widgets/EventListItem.dart
> +          width: isSmallSizeScreen ? double.infinity : 500,
Логично, я просто хотел для наглядности, как оно выглядить будет.
А у самого ListView кажется ширину установить нельзя и придется его в Container поместить

2023-05-31 20:15 UTC, ArkadiiIL commented on lib/widgets/EventListItem.dart
> +        Container(
У контейнера больше настроек, поэтому решил его оставить

2023-05-31 20:22 UTC, ArkadiiIL commented on assets/images/test_image.jpg
Да, что-то я не подумал, я так понял Image.network использовать

2023-05-31 20:31 UTC, ArkadiiIL commented on lib/widgets/EventListItem.dart
> +  });
На весь ListItem или только на link?
На link я думал сделать через TextButton, но в макете там больше похоже на классическую ссылку в тексте.

2023-06-01 05:13 UTC, IlyaGulya commented on lib/widgets/EventListItem.dart
> +  });
> На весь ListItem или только на link? На link я думал сделать через TextButton, но в макете там больше похоже на классическую ссылку в тексте.

На весь. Помимо ссылки мы же потом будем кликать на айтем и открывать экран с деталями события

2023-06-01 05:14 UTC, IlyaGulya commented on lib/widgets/EventListItem.dart
> +          width: isSmallSizeScreen ? double.infinity : 500,
> Логично, я просто хотел для наглядности, как оно выглядить будет. А у самого ListView кажется ширину установить нельзя и придется его в Container поместить

Ну я так понимаю что это так и работает во флаттере - хочешь паддинги/размеры - пихай в специальный виджет который отвечает за это.

2023-06-01 05:14 UTC, IlyaGulya commented on lib/widgets/EventListItem.dart
> +        Container(
Ну это up to you, я не думаю что это сильно важно.
Тут скорее написал потому что я щас накручу линтер на пулл реквесты и он всё равно будет ругаться на это =)

2023-06-01 05:15 UTC, IlyaGulya commented on assets/images/test_image.jpg
> Да, что-то я не подумал, я так понял Image.network использовать

Пока думаю хватит и Image.network, потом будем разбираться нужно ли отдельную библиотеку для картинок или нет

2023-06-01 10:52 UTC, ArkadiiIL commented
Я поправил

2023-06-01 11:20 UTC, IlyaGulya approved these changes
LGTM

2023-06-01 11:20 UTC, merged