st 23 UI add bottom navigation
openworld-community/ows-events-mobile pull request #39
Opened 2023-06-19 15:45 UTC by leksidev

2023-06-19 18:24 UTC, MariannaKhanina requested changes

2023-06-19 18:24 UTC, MariannaKhanina commented on lib/features/main/presentation/main_screen.dart
> +                    ref.read(indexProvider.notifier).value = index),
тут после index надо добавить запятую, без нее едет форматирование. Еще можно этот обработчик вынести в приватный метод этого класса

2023-06-19 18:24 UTC, MariannaKhanina commented on lib/features/main/presentation/main_screen.dart
> +                    curve: Curves.easeInOut);
тут тоже надо добавить запятую перед закрывающей скобкой

2023-06-19 18:24 UTC, MariannaKhanina commented on lib/features/main/presentation/main_screen.dart
> +    final int menuIndex = ref.watch(indexProvider) as int;
не уверена, что нам тут нужно текущий индекс хранить в провайдере. Если у нас не будет необходимости менять выбранный таб за пределами данного компонента - лучше переделать на StatefulWidget и хранить и менять текущий индекс в приватной переменной этого класса.

2023-06-19 19:38 UTC, leksidev commented on lib/features/main/presentation/main_screen.dart
> +    final int menuIndex = ref.watch(indexProvider) as int;
Я предполагаю, что необходимость будет. Например, я добавляю в избранное и у меня всплывает окошко с предложением перейти в избранное. По примеру,к ак когда на маркетплейсе в корзину добавляешь товар и сразу есть вариант перейти в корзину без лишних телодвижений.

2023-06-20 07:39 UTC, MariannaKhanina requested changes

2023-06-20 10:28 UTC, MariannaKhanina approved these changes

2023-06-20 10:28 UTC, merged